name: Release

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        node-version: [20]
        pnpm-version: [latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - uses: pnpm/action-setup@v3.0.0
        with:
          version: ${{ matrix.pnpm-version }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Build Windows App
        if: matrix.platform == 'windows-latest'
        uses: tauri-apps/tauri-action@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_ENV: production
        with:
          tagName: v__VERSION__-build # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__ Build'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          includeDebug: false
          prerelease: false
